# Site settings
title: ShardedInsights
email: praveen7484@gmail.com
description: >- 
  ./configure --with-distributed-systems --enable-data-science
  Signals, patterns, and scalable solutions from the command line to the cloud.
baseurl: "" # empty for user/organization site
url: "https://shardedinsights.github.io" # the base hostname & protocol for your site

# Author information
author:
  name: Praveen Kannan
  bio: >-
    Technology leader specializing in distributed systems architecture and scalable data solutions.
    Solving enterprise-scale challenges with elegant technical design and strategic thinking.
  location: "Global"
  twitter: sigpipe
  github: praveenkannan
  linkedin: praveenkannan

# Build settings
markdown: kramdown
remote_theme: hydecorp/hydejack@v9.1.6 # Modern theme with excellent typography
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache # Required by Hydejack

# Theme-specific settings
logo: /assets/img/logo.png
favicon: /assets/img/favicon.png
accent_image: /assets/img/sidebar-bg.jpg
accent_color: '#202020'

# Customization
theme_color: '#202020'
hydejack:
  dark_mode:
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true
  no_drawer: false
  no_navbar: false
  no_search: false
  no_inline_css: false
  no_push_state: false
  no_toc: false
  no_third_party: false
  offline:
    enabled: true
    cache_version: 1

# Navigation - Unix-style naming
menu:
  - title: ~/about
    url: /usr/bin/about/
  - title: ~/projects
    url: /var/projects/
  - title: ~/blog
    url: /var/log/blog/
  - title: ~/contact
    url: /etc/contact/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num/"

# Footer settings
footer_links:
  - title: GitHub
    url: https://github.com/praveenkannan
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/praveenkannan
    icon: fab fa-linkedin
  - title: Twitter
    url: https://twitter.com/sigpipe
    icon: fab fa-twitter

# SEO settings
twitter:
  username: sigpipe
  card: summary
social:
  name: Praveen Kannan
  links:
    - https://twitter.com/sigpipe
    - https://www.linkedin.com/in/praveenkannan
    - https://github.com/praveenkannan

# Google Analytics
google_analytics: G-XPTTFW2DDH

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - CNAME
