# Site settings
title: ShardedInsights
email: praveen7484@gmail.com
description: >- 
  ./configure --with-distributed-systems --enable-data-science
  Signals, patterns, and scalable solutions from the command line to the cloud.
baseurl: "" # empty for user/organization site
url: "https://shardedinsights.github.io" # the base hostname & protocol for your site

# Author information
author:
  name: Praveen Kannan
  bio: >-
    Technology leader specializing in distributed systems architecture and scalable data solutions.
    Solving enterprise-scale challenges with elegant technical design and strategic thinking.
  location: "Global"
  twitter: sigpipe
  github: praveenkannan
  linkedin: praveenkannan

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal # Clean, professional theme better for leadership presence
remote_theme: pages-themes/minimal@v0.2.0 # Ensures the theme works with GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme # Added to support remote themes

# Theme-specific settings
logo: /assets/img/logo.png # Add a professional logo/headshot
show_downloads: false
google_analytics: G-XPTTFW2DDH # Replace with your actual Measurement ID

# Navigation - Unix-style naming
header_pages:
  - usr/bin/about.md
  - var/projects.md
  - var/log/blog.md
  - etc/contact.md

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num/"

# Disqus comments (optional)
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - CNAME
