# Site settings
title: "Sharded Insights"
description: "Exploring software engineering, AI, cloud technologies, and innovative tech solutions. Join me in unraveling complex tech concepts."
baseurl: "" # The subpath of your site, e.g. /blog/
url: "https://praveenkannan.github.io" # The base hostname & protocol for your site
domain: "praveenkannan.github.io"

# SEO and Privacy Settings
webmaster_verifications:
  google: ""  # Optional: Add Google Search Console verification
  bing: ""    # Optional: Add Bing Webmaster Tools verification

# Robots and Crawling
defaults:
  -
    scope:
      path: ""
    values:
      robots: "index, follow"
      image: /assets/img/site-preview.png
      og:
        type: article
      twitter:
        card: summary_large_image

# Build settings
markdown: kramdown
remote_theme: hydecorp/hydejack@v9.1.6

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-compress-images

# Theme Configuration
hydejack:
  # Set to `true` if you want to add a dark mode toggle
  dark_mode: true
  
  # Set to `true` if you want to use the logo as a background for the entire page
  background_image: false
  
  # Set the color accent for the theme
  accent_color: '#4fb1ba'
  
  # Set the theme color
  theme_color: '#4fb1ba'
  
  # Enable or disable features
  features:
    - navigation
    - search
    - dark_mode
    - comments
    - related_posts
    - project_card
    - blog_card
  
  # Disqus Comments
  disqus: false
  
  # Google Analytics
  google_analytics: G-XPTTFW2DDH

# Author Settings
author:
  name: "Praveen Kannan"
  avatar: "/assets/img/avatar.jpg"
  bio: "Software Engineer | AI Enthusiast | Cloud Technologies"
  location: "San Francisco, CA"
  email: "praveen.kannan@example.com"
  social:
    linkedin: "praveenkannan"
    github: "praveenkannan"
    twitter: "praveenkannan"

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .github
  - README.md
  - LICENSE
  - CNAME

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Ensure Jekyll generates links correctly
relative_permalinks: false
