# Site settings
title: SharededInsights
email: praveen7484@gmail.com
description: >- 
  ./configure --with-distributed-systems --enable-data-science
  Signals, patterns, and scalable solutions from the command line to the cloud.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sigsage.io" # the base hostname & protocol for your site

# Author information
author:
  name: Praveen Kannan
  bio: >-
    #!/usr/bin/env human
    Distributed systems architect debugging complexity at scale.
    Signal processor, pattern matcher, failure investigator.
  location: "~/current/location"
  twitter: sigpipe
  github: praveenkannan
  linkedin: praveenkannan

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker # GitHub Pages supported theme with a hacker/terminal aesthetic
remote_theme: pages-themes/hacker@v0.2.0 # Ensures the theme works with GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme # Added to support remote themes

# Theme-specific settings
theme_settings:
  show_downloads: false # Hide download buttons in header
  google_analytics: # Add your GA ID if needed
  header_text: "~/distributed-systems $ ./share-insights"
  syntax_highlighting: true

# Navigation - Unix-style naming
header_pages:
  - usr/bin/about.md
  - var/projects.md
  - var/log/blog.md
  - etc/contact.md

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num/"

# Disqus comments (optional)
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - CNAME
